# Create persistent volume for stateful use
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-master
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce  
  gcePersistentDisk:
    pdName: models-master
    fsType: xfs