# Create persistent volume for stateful use
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-master-2
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/"
  # gcePersistentDisk:
  #   pdName: models-master
  #   fsType: xfs