# Create persistent volume for stateful use
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-data
spec:
  capacity:
    storage: 200Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce  
  gcePersistentDisk:
    pdName: models-data
    fsType: xfs