# Create persistent volume for stateful use
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv001
  labels:
    name: model-01
spec:
  capacity:
    storage: 100Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: models-1-0-0
    fsType: ext4
    readOnly: true