apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "fast" 
spec:
  capacity:
    storage: "50Gi" 
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk: 
    fsType: "ext4" 
    pdName: "pd-disk-1" 