apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ingest
  annotations: 
    cloud.google.com/load-balancer-type: Internal
  labels:
    component: elasticsearch
    role: ingest
spec:
  selector:
    component: elasticsearch
    role: ingest
  ports:
  - name: http
    port: 9200
  type: LoadBalancer
  # externalIPs:
  # - 10.0.0.150